name: Build Docker - mediasoup-demo-onebox 

on: 
  push:
    branches:
    - 'main'

env:
  IMAGE_NAME: mediasoup-demo-onebox
  DOCKERFILE_PATH: ./

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    # - name: Prepare config
    #   run: cd server && cp config.example.js config.js
    # - name: Prepare Certs
    #   run: cd server && mkdir -p certs && cd certs && openssl genrsa > privkey.pem && openssl req -new -x509 -key privkey.pem -subj "/C=CN/ST=SH/L=Springfield/O=Dis/CN=www.example.com" > fullchain.pem

    - name: Build & Publish to Github Container Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.actor }}/${{ env.IMAGE_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        snapshot: false
        workdir: ${{ env.DOCKERFILE_PATH }}
        tags: "latest"

