name: Build Docker - mediasoup-demo 

on: 
  push:
    branches:
    - 'main'

env:
  IMAGE_NAME: mediasoup-demo
  DOCKERFILE_PATH: server

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build & Publish to Github Container Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.actor }}/${{ env.IMAGE_NAME }}
        username: ${{ github.actor }}
        password: ${{ secrets.WRITE_PACKAGES_TOKEN }}
        registry: ghcr.io
        snapshot: false
        workdir: ${{ env.DOCKERFILE_PATH }}
        tags: "latest"

